language: go

go:
  - 1.8

os:
  - linux

sudo: false

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

before_script:
  - glide install

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - overalls -project=github.com/l10n-center/api -- -race -v

after_script:
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci

notifications:
  email: true
