# This file used only for developing
version: '2'
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "16686:16686"
