# This file used only for developing
version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "16686:16686"
