// Automatically generated by MockGen. DO NOT EDIT!
// Source: store.go

package auth_test

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/l10n-center/api/src/model"
	bson "gopkg.in/mgo.v2/bson"
)

// Mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *_MockStoreRecorder
}

// Recorder for MockStore (not exported)
type _MockStoreRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &_MockStoreRecorder{mock}
	return mock
}

func (_m *MockStore) EXPECT() *_MockStoreRecorder {
	return _m.recorder
}

func (_m *MockStore) GetUserCount(_param0 context.Context) (int, error) {
	ret := _m.ctrl.Call(_m, "GetUserCount", _param0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) GetUserCount(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetUserCount", arg0)
}

func (_m *MockStore) GetUserByID(_param0 context.Context, _param1 bson.ObjectId) (*model.User, error) {
	ret := _m.ctrl.Call(_m, "GetUserByID", _param0, _param1)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetUserByID", arg0, arg1)
}

func (_m *MockStore) GetUserByEmail(_param0 context.Context, _param1 string) (*model.User, error) {
	ret := _m.ctrl.Call(_m, "GetUserByEmail", _param0, _param1)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetUserByEmail", arg0, arg1)
}

func (_m *MockStore) CreateUser(_param0 context.Context, _param1 *model.User) error {
	ret := _m.ctrl.Call(_m, "CreateUser", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateUser", arg0, arg1)
}
